GET http://localhost:3000/teams

###

GET http://localhost:3000/teams/1


####

POST http://localhost:3000/teams
Content-Type: application/json

{
  "name": "pirates",
  "record": "21-9"
}
###
PATCH http://localhost:3000/teams/4
Content-Type: application/json

{
  "name": "The Pirates"
}

####

DELETE http://localhost:3000/teams/4